### ISSUE TITLE
Customized word not being ignored

### ISSUE THREAD

**Issue by cfjedimaster** [fgborges/textlint-rule-spelling#3]
I've got this for skipPatterns:

```
    "spelling":{
      "language":"en-us",
      "skipPatterns":["APPLY_URL", "<.*?>","<samp>","</samp>","<li>","</li>","OAuth","JWE"]
    }
```

And yet I'm still seeing APPLY_URL in the list of issues:

![image](https://user-images.githubusercontent.com/393660/59057344-d054cd80-885f-11e9-8abf-ba4495ab3c22.png)

**Comment by fgborges** [comment]
Hi @cfjedimaster, Thanks for your report.
I updated the package. I hope this change fix your issue.
Please, reinstall latest one.
Cheers.

**Comment by cfjedimaster** [comment]
Is it published to npm?

**Comment by fgborges** [comment]
Yes :wink:

**Comment by cfjedimaster** [comment]
I've removed it via npm and added it a few times now, same issue. Can you confirm what version I should see?

**Comment by fgborges** [comment]
OK, could you show me your environment?
My environmet is follow:
- package.json
```json
  "dependencies": {
    "textlint": "^11.2.5",
    "textlint-rule-spelling": "^0.1.1",
    "textlint-plugin-html": "^0.2.0"
  }
```
- .textlintrc
```json
{
  "plugins": ["html"],
  "rules": {
    "spelling": {
      "language": "en-us",
      "skipPatterns": ["APPLY_URL"]
    }
  }
}
```
- index.html
```html
<!DOCTYPE>
<html>
    <body>
        <p>
        APPLY_URL should be fixed
        </p>
    </body>
</html>
```
- `$ npx textlint --debug index.html`
```
  textlint:cli textlint --version: 11.2.5 +0ms
  textlint:cli Running on files, stdin-filename: undefined +1ms
  textlint:module-loader config Config {
  textlint:module-loader   configFile: '/home/fgborges/textlint-rule-spelling-test-2/.textlintrc',
  textlint:module-loader   rulesBaseDirectory: undefined,
  textlint:module-loader   disabledRules: [],
  textlint:module-loader   rules: [ 'spelling' ],
  textlint:module-loader   disabledFilterRules: [],
  textlint:module-loader   filterRules: [],
  textlint:module-loader   presets: [],
  textlint:module-loader   plugins: [ 'html' ],
  textlint:module-loader   pluginsConfig: { html: true },
  textlint:module-loader   rulesConfig: { spelling: { language: 'en-us', skipPatterns: [Array] } },
  textlint:module-loader   filterRulesConfig: {},
  textlint:module-loader   rulePaths: [],
  textlint:module-loader   formatterName: undefined,
  textlint:module-loader   quiet: false,
  textlint:module-loader   color: true,
  textlint:module-loader   cache: false,
  textlint:module-loader   cacheLocation:
  textlint:module-loader    '/home/fgborges/textlint-rule-spelling-test-2/.textlintcache' } +0ms
  textlint:module-loader Loading rules from /home/fgborges/textlint-rule-spelling-test-2/node_modules/textlint-rule-spelling/lib/index.js +4ms
  textlint:module-loader Loading rules from plugin: /home/fgborges/textlint-rule-spelling-test-2/node_modules/textlint-plugin-html/lib/index.js +14ms
  textlint:engine-core Process files [ '/home/fgborges/textlint-rule-spelling-test-2/index.html' ] +0ms
  textlint:engine-core No Process files that are un-support extensions: [] +0ms
  textlint:kernel available extensions: [ '.htm', '.html', '.md', '.markdown', '.mdown', '.mkdn', '.mkd', '.mdwn', '.mkdown', '.ron', '.txt', '.text' ] +0ms
  textlint:kernel use plugin: html +0ms
  textlint:cli lint results: [{"messages":[],"filePath":"/home/fgborges/textlint-rule-spelling-test-2/index.html"}] +253ms
  textlint:@textlint/linter-formatter formatterName: stylish +0ms
```
I have to know the minimal reproducible environment to know your issue more.
Please paste here your environment **fully**.

**Comment by cfjedimaster** [comment]
I think it's caching on my side. I'm behind like the largest firewall/vpn/etc ever. May switch to my personal machine to continue testing (and it will be in the morning - so forgive the delay :)

**Comment by cfjedimaster** [comment]
Confirmed I have 0.1.1, and APPLY_URL is still being flagged.

**Comment by fgborges** [comment]
Okay, let me know the minimal reproducible environment to test your issue.
Please paste here your environment.
At least, 
- package.json
- textlintrc
- test code (html text)
- log of ‘textlint —debug <your file>’

**Comment by cfjedimaster** [comment]
Hey I'm sorry - this is an HTML file. Would that be the issue? I logged the other one about having the rule ignore HTML tags.

**Comment by cfjedimaster** [comment]
I tried with a much smaller html file:

```
this is APPLY_URL test i cantt spell
```

No tags. And it doesn't flag APPLY_URL or `cantt`.

**Comment by cfjedimaster** [comment]
I copied the text above to a markdown file and it worked perfectly. Reported the right words and ignored APPLY_URL.

**Comment by fgborges** [comment]
> Hey I'm sorry - this is an HTML file. Would that be the issue? I logged the other one about having the rule ignore HTML tags.

Yes, I think so. However, in my case (see above my environment), it works perfectly for me. I guess your issue consists by some of problems. I'd like to see it locally.

> I tried with a much smaller html file:
> this is APPLY_URL test i cantt spell
> No tags. And it doesn't flag APPLY_URL or cantt.

textlint watches the text inside 'p' tags. This should be flagged if the text no surrounded by any tags.

> I copied the text above to a markdown file and it worked perfectly. Reported the right words and ignored APPLY_URL.

Me too. I've tested it locally and by every releases.
Again, Could you show me a minimal reproducible test case?
Please paste it here, or upload to GitHub as the repository and share the link to me.

Thank you for checking some cases, Could you share it for me?
- package.json
- .textlintrc
. HTML file
- log for `textlint --debug <your code>`

**Comment by cfjedimaster** [comment]
Adding the `<p>` tags worked fine. I'd argue it shouldn't be required since HTML is so loose, but that would be me being picky. I think this is good now, and thank you for your patience.

**Comment by fgborges** [comment]
> I'd argue it shouldn't be required since HTML is so loose, but that would be me being picky.
I understand and agree your opinion. Since that, I have to solve the issue #2 to work inside not only `Paragraph` nodes but also `Str` nodes. Please check the issue #2 . I notice your the project progress there.

**Comment by cfjedimaster** [comment]
Wow nice, and thank you again!
